### ISSUE TITLE
Helm chart installation failing due to duplicate key in template file

### ISSUE THREAD

**Issue by BrentGruber** [mistio/mist-ce#1045]
In the helm chart template elasticsearch-manage-job.yaml, there is a duplicate "name" key under metadata which is leading to this error while I am trying to install via Kustomize with helmChartInflationGenerator

```
error: map[string]interface {}(nil): yaml: unmarshal errors: 
  line 6: mapping key "name" already defined at line 5
```

Duplicate key can be found here:

https://github.com/mistio/mist-ce/blob/master/chart/mist/templates/elasticsearch-manage-job.yaml#L4

```
apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-manage
  name: {{ include "chart.fullname" . }}-elasticsearch-manage
```
